#em prod o container do mongodb está sendo gerenciado por outro serviço
#separado no servidor

services:
  chico:
    build:
      context: .
      dockerfile: dockerfile
    container_name: chico
    networks:
      - local
    ports:
      - '3000'
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    restart: unless-stopped

networks:
  local:
    external: true