services:
  mongodb:
    image: mongo:latest
    build:
      context: .
      dockerfile: dockerfile.mongodb
    container_name: mongodb
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
  chico:
    build:
      context: .
      dockerfile: dockerfile
    container_name: chico
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    restart: unless-stopped
    depends_on:
      - mongodb
volumes:
  mongo_data:
